export const GET_APPLICANTS_LIST = 'GET_APPLICANTS_LIST'
export const LOADING_TOGGLE = 'LOADING_TOGGLE'
export const DELETE_APPLICANTS_LIST = 'DELETE_APPLICANTS_LIST'
export const FILTER_APPLICANTS_BY_HOUSE = 'FILTER_APPLICANTS_BY_HOUSE'